// <auto-generated />
using System;
using DiplomProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomProject.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220509132211_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("DiplomProject.Data.Area", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id"));

                    b.Property<long?>("Streetid")
                        .HasColumnType("bigint");

                    b.Property<int>("parkingPlaces")
                        .HasColumnType("integer");

                    b.Property<int>("placesAmount")
                        .HasColumnType("integer");

                    b.Property<int>("rentPrice")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Streetid");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("DiplomProject.Data.Street", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numbersOfHouses")
                        .HasColumnType("integer");

                    b.Property<string>("typeOfHouses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("streets");
                });

            modelBuilder.Entity("DiplomProject.Data.Area", b =>
                {
                    b.HasOne("DiplomProject.Data.Street", null)
                        .WithMany("areas")
                        .HasForeignKey("Streetid");
                });

            modelBuilder.Entity("DiplomProject.Data.Street", b =>
                {
                    b.Navigation("areas");
                });
#pragma warning restore 612, 618
        }
    }
}
